### ISSUE TITLE
Problem with dynamic modals and babel-loader

### ISSUE THREAD

**Issue by pdesmarais** [euvl/vue-js-modal#402]
#### Problem: 

I am using dynamic modals everywhere in my app because it is simpler to manage the modals as Vue components. I've been experiencing a problem with the 1st modal being opened in a session. Really hard to build some code to be able to reproduce the exact problem. The issue I'm having is that on 1st modal load in a new browser session, the modal doesn't show BUT the `v--modal-block-scroll` class gets added to the body. The only way to fix the problem is to reload the page. Once the reload is complete, everything behaves normally; modals open as expected.

I've forked the repo to try to debug and the first thing that popped is that babel-loader is using `latest`. Here's the error I had on first build:

`Module build failed: Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.`

So, I went ahead and removed `babel-loader` from the package.json and installed it again using `npm install babel-loader@7` because the module's package.json EXPLICITLY uses `"babel-core": "^6.25.0"` but using latest for babel-loader uses a much newer version of babel-loader which would need a newer version of babel-core.

From that moment, although the dist files were not uglified, my problem with the initial modal not showing went away. I also added the `-p` flag to the build tasks so it would uglify properly and still, initial modal would show normally.

Is it possible that there's something that doesn't compile properly using the latest babel-loader and that `vue-js-modal` should use babel-loader@7?

Thanks for looking into this. I'd prefer not having to use a fork of your project and use the real thing.

**Comment by io-ma** [comment]
I am having the exact problem, my modal is not being recognized because I MUST use an earlier version of babel in my project. Is there anything I can do to make it work with babel-core 6.26?
